[package]
name = "rokugo-query"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
rustc-hash = "1.1.0"
parking_lot.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "fib"
harness = false
