[package]
name = "rokugo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }

rokugo-ast.workspace = true
rokugo-lexis.workspace = true
rokugo-parser.workspace = true
